% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:02:32
% Model: aircrftb

% Objective
fun = @(x)(8.39*x(3)*x(4)-0.727*x(2)*x(3)-684.4*x(4)*x(5)+63.5*x(4)*x(2)+0.107*x(2)+0.126*x(3)-9.99*x(5)-3.933*x(1)-45.83*x(7)-7.64*x(8))^2+(0.949*x(1)*x(3)+0.173*x(1)*x(5)-0.987*x(2)-22.95*x(4)-28.37*x(6))^2+(-0.716*x(1)*x(2)-1.578*x(1)*x(4)+1.132*x(4)*x(2)+0.002*x(1)-0.235*x(3)+5.67*x(5)-0.921*x(7)-6.51*x(8))^2+(x(2)-x(1)*x(5)-x(4)-0.168*x(6))^2+(x(1)*x(4)-x(3)-0.196*x(5)-0.0071*x(7))^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-0.05,0.1,0]';
ub = [Inf,Inf,Inf,Inf,Inf,-0.05,0.1,0]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,-0.05,0.1,NaN]';

% Options
opts = struct('probname','aircrftb');
opts.sense = 'min';
