% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:02:40
% Model: bard

% Objective
fun = @(x)(0.14-1/(15*x(2)+x(3))-x(1))^2+(0.18-2/(14*x(2)+2*x(3))-x(1))^2+(0.22-3/(13*x(2)+3*x(3))-x(1))^2+(0.25-4/(12*x(2)+4*x(3))-x(1))^2+(0.29-5/(11*x(2)+5*x(3))-x(1))^2+(0.32-6/(10*x(2)+6*x(3))-x(1))^2+(0.35-7/(9*x(2)+7*x(3))-x(1))^2+(0.39-8/(8*x(2)+8*x(3))-x(1))^2+(0.37-9/(7*x(2)+7*x(3))-x(1))^2+(0.58-10/(6*x(2)+6*x(3))-x(1))^2+(0.73-11/(5*x(2)+5*x(3))-x(1))^2+(0.96-12/(4*x(2)+4*x(3))-x(1))^2+(1.34-13/(3*x(2)+3*x(3))-x(1))^2+(2.1-14/(2*x(2)+2*x(3))-x(1))^2+(4.39-15/(x(2)+x(3))-x(1))^2;

% Bounds
lb = [-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [1,1,1]';

% Options
opts = struct('probname','bard');
opts.sense = 'min';
