% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:02:31
% Model: BeckerLago

% Objective
fun = @(x)(-5+(x(1)^2)^0.5)*(-5+(x(1)^2)^0.5)+(-5+(x(2)^2)^0.5)*(-5+(x(2)^2)^0.5);

% Bounds
lb = [-10,-10]';
ub = [10,10]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','BeckerLago');
opts.sense = 'min';
