% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:03:27
% Model: camel1

% Objective
fun = @(x)4*x(1)^2-2.1*x(1)^4+0.333333333333333*x(1)*x(1)*x(1)*x(1)*x(1)*x(1)+x(1)*x(2)-4*x(2)^2+4*x(2)^4;

% Bounds
lb = [-5,-5]';
ub = [5,5]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [1,1]';

% Options
opts = struct('probname','camel1');
opts.sense = 'min';
