% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:03:29
% Model: chnrosnb

% Objective
fun = @(x)31.36*(x(1)-x(2)^2)^2+(-1+x(2))^2+92.16*(x(2)-x(3)^2)^2+(-1+x(3))^2+31.36*(x(3)-x(4)^2)^2+(-1+x(4))^2+49*(x(4)-x(5)^2)^2+(-1+x(5))^2+23.04*(x(5)-x(6)^2)^2+(-1+x(6))^2+81*(x(6)-x(7)^2)^2+(-1+x(7))^2+23.04*(x(7)-x(8)^2)^2+(-1+x(8))^2+16*(x(8)-x(9)^2)^2+(-1+x(9))^2+19.36*(x(9)-x(10)^2)^2+(-1+x(10))^2+36*(x(10)-x(11)^2)^2+(-1+x(11))^2+40.96*(x(11)-x(12)^2)^2+(-1+x(12))^2+25*(x(12)-x(13)^2)^2+(-1+x(13))^2+25*(x(13)-x(14)^2)^2+(-1+x(14))^2+23.04*(x(14)-x(15)^2)^2+(-1+x(15))^2+23.04*(x(15)-x(16)^2)^2+(-1+x(16))^2+31.36*(x(16)-x(17)^2)^2+(-1+x(17))^2+4*(x(17)-x(18)^2)^2+(-1+x(18))^2+4*(x(18)-x(19)^2)^2+(-1+x(19))^2+25*(x(19)-x(20)^2)^2+(-1+x(20))^2+51.84*(x(20)-x(21)^2)^2+(-1+x(21))^2+9*(x(21)-x(22)^2)^2+(-1+x(22))^2+25*(x(22)-x(23)^2)^2+(-1+x(23))^2+31.36*(x(23)-x(24)^2)^2+(-1+x(24))^2+40.96*(x(24)-x(25)^2)^2+(-1+x(25))^2+64*(x(25)-x(26)^2)^2+(-1+x(26))^2+16*(x(26)-x(27)^2)^2+(-1+x(27))^2+40.96*(x(27)-x(28)^2)^2+(-1+x(28))^2+25*(x(28)-x(29)^2)^2+(-1+x(29))^2+121*(x(29)-x(30)^2)^2+(-1+x(30))^2+25*(x(30)-x(31)^2)^2+(-1+x(31))^2+25*(x(31)-x(32)^2)^2+(-1+x(32))^2+25*(x(32)-x(33)^2)^2+(-1+x(33))^2+144*(x(33)-x(34)^2)^2+(-1+x(34))^2+36*(x(34)-x(35)^2)^2+(-1+x(35))^2+64*(x(35)-x(36)^2)^2+(-1+x(36))^2+25*(x(36)-x(37)^2)^2+(-1+x(37))^2+31.36*(x(37)-x(38)^2)^2+(-1+x(38))^2+51.84*(x(38)-x(39)^2)^2+(-1+x(39))^2+36*(x(39)-x(40)^2)^2+(-1+x(40))^2+77.44*(x(40)-x(41)^2)^2+(-1+x(41))^2+31.36*(x(41)-x(42)^2)^2+(-1+x(42))^2+36*(x(42)-x(43)^2)^2+(-1+x(43))^2+25*(x(43)-x(44)^2)^2+(-1+x(44))^2+64*(x(44)-x(45)^2)^2+(-1+x(45))^2+36*(x(45)-x(46)^2)^2+(-1+x(46))^2+25*(x(46)-x(47)^2)^2+(-1+x(47))^2+31.36*(x(47)-x(48)^2)^2+(-1+x(48))^2+5.76*(x(48)-x(49)^2)^2+(-1+x(49))^2+36*(x(49)-x(50)^2)^2+(-1+x(50))^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','chnrosnb');
opts.sense = 'min';
