% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:03:53
% Model: concha11

% Objective
fun = @(x)(1-exp(x(2))*x(1))^2+(1-exp(x(2))*x(1))^2+(3-exp(0.5*x(2))*x(1))^2+(4-exp(0.333333333333333*x(2))*x(1))^2+(7-exp(0.25*x(2))*x(1))^2+(11-exp(0.2*x(2))*x(1))^2+(18-exp(0.166666666666667*x(2))*x(1))^2+(29-exp(0.142857142857143*x(2))*x(1))^2+(47-exp(0.125*x(2))*x(1))^2+(76-exp(0.111111111111111*x(2))*x(1))^2+(123-exp(0.1*x(2))*x(1))^2+(199-exp(0.0909090909090909*x(2))*x(1))^2+(322-exp(0.0833333333333333*x(2))*x(1))^2+(521-exp(0.0769230769230769*x(2))*x(1))^2+(843-exp(0.0714285714285714*x(2))*x(1))^2+(1364-exp(0.0666666666666667*x(2))*x(1))^2+(2207-exp(0.0625*x(2))*x(1))^2+(3571-exp(0.0588235294117647*x(2))*x(1))^2+(5778-exp(0.0555555555555556*x(2))*x(1))^2+(9529-exp(0.0526315789473684*x(2))*x(1))^2+(15307-exp(0.05*x(2))*x(1))^2+(24836-exp(0.0476190476190476*x(2))*x(1))^2;

% Bounds
lb = [-10000,-10]';
ub = [10000,10]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','concha11');
opts.sense = 'min';
