% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:03:53
% Model: concha10

% Objective
fun = @(x)(1-exp(x(2))*x(1))^2+(1-exp(x(2))*x(1))^2+(3-exp(2*x(2))*x(1))^2+(4-exp(3*x(2))*x(1))^2+(7-exp(4*x(2))*x(1))^2+(11-exp(5*x(2))*x(1))^2+(18-exp(6*x(2))*x(1))^2+(29-exp(7*x(2))*x(1))^2+(47-exp(8*x(2))*x(1))^2+(76-exp(9*x(2))*x(1))^2+(123-exp(10*x(2))*x(1))^2+(199-exp(11*x(2))*x(1))^2+(322-exp(12*x(2))*x(1))^2+(521-exp(13*x(2))*x(1))^2+(843-exp(14*x(2))*x(1))^2+(1364-exp(15*x(2))*x(1))^2+(2207-exp(16*x(2))*x(1))^2+(3571-exp(17*x(2))*x(1))^2+(5778-exp(18*x(2))*x(1))^2+(9529-exp(19*x(2))*x(1))^2+(15307-exp(20*x(2))*x(1))^2+(24836-exp(21*x(2))*x(1))^2;

% Bounds
lb = [-10000,-1]';
ub = [10000,1]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','concha10');
opts.sense = 'min';
