% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:05:34
% Model: dixon3dq

% Objective
fun = @(x)(-1+x(1))^2+(x(2)-x(3))^2+(x(3)-x(4))^2+(x(4)-x(5))^2+(x(5)-x(6))^2+(x(6)-x(7))^2+(x(7)-x(8))^2+(x(8)-x(9))^2+(x(9)-x(10))^2+(-1+x(10))^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]';

% Options
opts = struct('probname','dixon3dq');
opts.sense = 'min';
