% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:05:49
% Model: draperg

% Objective
fun = @(x)(490.2-log(40*x(2)+x(3))*x(1))^2+(585.3-log(80*x(2)+x(3))*x(1))^2+(673.7-log(160*x(2)+x(3))*x(1))^2+(759.2-log(320*x(2)+x(3))*x(1))^2+(837.5-log(640*x(2)+x(3))*x(1))^2;

% Bounds
lb = [1,1,-30]';
ub = [1000,100,100]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [1,1,NaN]';

% Options
opts = struct('probname','draperg');
opts.sense = 'min';
