% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:02:31
% Model: Expo

% Objective
fun = @(x)-exp(-0.5*(x(1)*x(1)+x(2)*x(2)+x(3)*x(3)+x(4)*x(4)+x(5)*x(5)+x(6)*x(6)+x(7)*x(7)+x(8)*x(8)+x(9)*x(9)+x(10)*x(10)));

% Bounds
lb = [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]';
ub = [1,1,1,1,1,1,1,1,1,1]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','Expo');
opts.sense = 'min';
