% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:06:02
% Model: gold

% Objective
fun = @(x)(1+(1+x(1)+x(2))^2*(19+3*x(1)^2-14*x(1)+6*x(1)*x(2)-14*x(2)+3*x(2)^2))*(30+(2*x(1)-3*x(2))^2*(18+12*x(1)^2-32*x(1)-36*x(1)*x(2)+48*x(2)+27*x(2)^2));

% Bounds
lb = [-2,-2]';
ub = [2,2]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [0.5,-0.5]';

% Options
opts = struct('probname','gold');
opts.sense = 'min';
