% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:02:31
% Model: Hartman3

% Objective
fun = @(x)-(exp(-(3*(-0.3689+x(1))^2+10*(-0.117+x(2))^2+30*(-0.2673+x(3))^2))+1.2*exp(-(0.1*(-0.4699+x(1))^2+10*(-0.4387+x(2))^2+35*(-0.747+x(3))^2))+3*exp(-(3*(-0.1091+x(1))^2+10*(-0.8732+x(2))^2+30*(-0.5547+x(3))^2))+3.2*exp(-(0.1*(-0.03815+x(1))^2+10*(-0.5743+x(2))^2+35*(-0.8828+x(3))^2)));

% Bounds
lb = [0,0,0]';
ub = [1,1,1]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','Hartman3');
opts.sense = 'min';
