% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:06:02
% Model: hatflda

% Objective
fun = @(x)(-1+x(1))^2+(x(1)-x(2)^0.5)^2+(x(2)-x(3)^0.5)^2+(x(3)-x(4)^0.5)^2;

% Bounds
lb = [1e-07,1e-07,1e-07,1e-07]';
ub = [Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [0.1,0.1,0.1,0.1]';

% Options
opts = struct('probname','hatflda');
opts.sense = 'min';
