% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:06:02
% Model: heart8ls

% Objective
fun = @(x)(0.69+x(1)+x(2))*(0.69+x(1)+x(2))+(0.044+x(3)+x(4))*(0.044+x(3)+x(4))+(1.57+x(5)*x(1)+x(6)*x(2)-x(7)*x(3)-x(8)*x(4))*(1.57+x(5)*x(1)+x(6)*x(2)-x(7)*x(3)-x(8)*x(4))+(1.31+x(7)*x(1)+x(8)*x(2)+x(5)*x(3)+x(6)*x(4))*(1.31+x(7)*x(1)+x(8)*x(2)+x(5)*x(3)+x(6)*x(4))+(2.65+(x(5)*x(5)-x(7)*x(7))*x(1)-2*x(3)*x(5)*x(7)+(x(6)*x(6)-x(8)*x(8))*x(2)-2*x(4)*x(6)*x(8))*(2.65+(x(5)*x(5)-x(7)*x(7))*x(1)-2*x(3)*x(5)*x(7)+(x(6)*x(6)-x(8)*x(8))*x(2)-2*x(4)*x(6)*x(8))+(-2+(x(5)*x(5)-x(7)*x(7))*x(3)+2*x(1)*x(5)*x(7)+(x(6)*x(6)-x(8)*x(8))*x(4)+2*x(2)*x(6)*x(8))*(-2+(x(5)*x(5)-x(7)*x(7))*x(3)+2*x(1)*x(5)*x(7)+(x(6)*x(6)-x(8)*x(8))*x(4)+2*x(2)*x(6)*x(8))+(12.6+x(1)*x(5)*(x(5)*x(5)-3*x(7)*x(7))+x(3)*x(7)*(x(7)*x(7)-3*x(5)*x(5))+x(2)*x(6)*(x(6)*x(6)-3*x(8)*x(8))+x(4)*x(8)*(x(8)*x(8)-3*x(6)*x(6)))*(12.6+x(1)*x(5)*(x(5)*x(5)-3*x(7)*x(7))+x(3)*x(7)*(x(7)*x(7)-3*x(5)*x(5))+x(2)*x(6)*(x(6)*x(6)-3*x(8)*x(8))+x(4)*x(8)*(x(8)*x(8)-3*x(6)*x(6)))+(-9.48+x(3)*x(5)*(x(5)*x(5)-3*x(7)*x(7))-x(1)*x(7)*(x(7)*x(7)-3*x(5)*x(5))+x(4)*x(6)*(x(6)*x(6)-3*x(8)*x(8))-x(2)*x(8)*(x(8)*x(8)-3*x(6)*x(6)))*(-9.48+x(3)*x(5)*(x(5)*x(5)-3*x(7)*x(7))-x(1)*x(7)*(x(7)*x(7)-3*x(5)*x(5))+x(4)*x(6)*(x(6)*x(6)-3*x(8)*x(8))-x(2)*x(8)*(x(8)*x(8)-3*x(6)*x(6)));

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [NaN,1,NaN,1,1,1,1,1]';

% Options
opts = struct('probname','heart8ls');
opts.sense = 'min';
