% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:02:31
% Model: Hosaki

% Objective
fun = @(x)(1+7*x(1)*x(1)-8*x(1)-2.33333333333333*x(1)*x(1)*x(1)+0.25*x(1)*x(1)*x(1)*x(1))*x(2)*x(2)*exp(-x(2));

% Bounds
lb = [0,0]';
ub = [5,6]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','Hosaki');
opts.sense = 'min';
