% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:06:03
% Model: hs045

% Objective
fun = @(x)-0.00833333333333333*x(1)*x(2)*x(3)*x(4)*x(5)+2;

% Bounds
lb = [0,0,0,0,0]';
ub = [1,2,3,4,5]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs045');
opts.sense = 'min';
