% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:07:17
% Model: kowalik

% Objective
fun = @(x)(0.1957-x(1)*(16+4*x(2))/(16+4*x(3)+x(4)))^2+(0.1947-x(1)*(4+2*x(2))/(4+2*x(3)+x(4)))^2+(0.1735-x(1)*(1+x(2))/(1+x(3)+x(4)))^2+(0.16-x(1)*(0.25+0.5*x(2))/(0.25+0.5*x(3)+x(4)))^2+(0.0844-x(1)*(0.0625+0.25*x(2))/(0.0625+0.25*x(3)+x(4)))^2+(0.0627-x(1)*(0.0277777777777778+0.166666666666667*x(2))/(0.0277777777777778+0.166666666666667*x(3)+x(4)))^2+(0.0456-x(1)*(0.015625+0.125*x(2))/(0.015625+0.125*x(3)+x(4)))^2+(0.0342-x(1)*(0.01+0.1*x(2))/(0.01+0.1*x(3)+x(4)))^2+(0.0323-x(1)*(0.00694444444444444+0.0833333333333333*x(2))/(0.00694444444444444+0.0833333333333333*x(3)+x(4)))^2+(0.0235-x(1)*(0.00510204081632653+0.0714285714285714*x(2))/(0.00510204081632653+0.0714285714285714*x(3)+x(4)))^2+(0.0246-x(1)*(0.00390625+0.0625*x(2))/(0.00390625+0.0625*x(3)+x(4)))^2;

% Bounds
lb = [0,0,0,0]';
ub = [0.42,0.42,0.42,0.42]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [0.42,0.42,0.42,0.42]';

% Options
opts = struct('probname','kowalik');
opts.sense = 'min';
