% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:01
% Model: median_vareps

% Objective
fun = @(x)(x(1)^2+(-0.171747132+x(2))^2)^0.5+(x(1)^2+(-0.843266708+x(2))^2)^0.5+(x(1)^2+(-0.550375356+x(2))^2)^0.5+(x(1)^2+(-0.301137904+x(2))^2)^0.5+(x(1)^2+(-0.292212117+x(2))^2)^0.5+(x(1)^2+(-0.224052867+x(2))^2)^0.5+(x(1)^2+(-0.349830504+x(2))^2)^0.5+(x(1)^2+(-0.856270347+x(2))^2)^0.5+(x(1)^2+(-0.067113723+x(2))^2)^0.5+(x(1)^2+(-0.500210669+x(2))^2)^0.5+(x(1)^2+(-0.998117627+x(2))^2)^0.5+(x(1)^2+(-0.578733378+x(2))^2)^0.5+(x(1)^2+(-0.991133039+x(2))^2)^0.5+(x(1)^2+(-0.762250467+x(2))^2)^0.5+(x(1)^2+(-0.130692483+x(2))^2)^0.5+(x(1)^2+(-0.639718759+x(2))^2)^0.5+(x(1)^2+(-0.159517864+x(2))^2)^0.5+(x(1)^2+(-0.250080533+x(2))^2)^0.5+(x(1)^2+(-0.668928609+x(2))^2)^0.5+x(1);

% Bounds
lb = [1e-08,-Inf]';
ub = [Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [1,0.5]';

% Options
opts = struct('probname','median_vareps');
opts.sense = 'min';
