% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:05
% Model: model19

% Objective
fun = @(x)(10.07-(1-exp(-77.6*x(2)))*x(1))^2+(14.73-(1-exp(-114.9*x(2)))*x(1))^2+(17.94-(1-exp(-141.1*x(2)))*x(1))^2+(23.93-(1-exp(-190.8*x(2)))*x(1))^2+(29.61-(1-exp(-239.9*x(2)))*x(1))^2+(35.18-(1-exp(-289*x(2)))*x(1))^2+(40.02-(1-exp(-332.8*x(2)))*x(1))^2+(44.82-(1-exp(-378.4*x(2)))*x(1))^2+(50.76-(1-exp(-434.8*x(2)))*x(1))^2+(55.05-(1-exp(-477.3*x(2)))*x(1))^2+(61.01-(1-exp(-536.8*x(2)))*x(1))^2+(66.4-(1-exp(-593.1*x(2)))*x(1))^2+(75.47-(1-exp(-689.1*x(2)))*x(1))^2+(81.78-(1-exp(-760*x(2)))*x(1))^2;

% Bounds
lb = [-1000,0]';
ub = [1000,1000]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','model19');
opts.sense = 'min';
