% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:05
% Model: model16

% Objective
fun = @(x)(0.1957-x(1)*(16+4*x(2))/(16+4*x(3)+x(4)))^2+(0.1947-x(1)*(4+2*x(2))/(4+2*x(3)+x(4)))^2+(0.1735-x(1)*(1+x(2))/(1+x(3)+x(4)))^2+(0.16-x(1)*(0.25+0.5*x(2))/(0.25+0.5*x(3)+x(4)))^2+(0.0844-x(1)*(0.0625+0.25*x(2))/(0.0625+0.25*x(3)+x(4)))^2+(0.0627-x(1)*(0.027889+0.167*x(2))/(0.027889+0.167*x(3)+x(4)))^2+(0.0456-x(1)*(0.015625+0.125*x(2))/(0.015625+0.125*x(3)+x(4)))^2+(0.0342-x(1)*(0.01+0.1*x(2))/(0.01+0.1*x(3)+x(4)))^2+(0.0323-x(1)*(0.006889+0.083*x(2))/(0.006889+0.083*x(3)+x(4)))^2+(0.0235-x(1)*(0.00509796+0.0714*x(2))/(0.00509796+0.0714*x(3)+x(4)))^2+(0.0246-x(1)*(0.00390625+0.0625*x(2))/(0.00390625+0.0625*x(3)+x(4)))^2;

% Bounds
lb = [0,0,0,0]';
ub = [2,2,2,2]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','model16');
opts.sense = 'min';
