% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:05
% Model: model42

% Objective
fun = @(x)(4.1-(1^x(2)*x(1)+exp(x(2)*log(x(3)))))^2+(3.3-(1.2^x(2)*x(1)+exp(x(2)*log(x(3)))))^2+(2.9-(1.4^x(2)*x(1)+exp(x(2)*log(x(3)))))^2+(2.7-(1.6^x(2)*x(1)+exp(x(2)*log(x(3)))))^2+(2.6-(1.8^x(2)*x(1)+exp(x(2)*log(x(3)))))^2+(2.7-(2^x(2)*x(1)+exp(x(2)*log(x(3)))))^2+(2.8-(2.2^x(2)*x(1)+exp(x(2)*log(x(3)))))^2+(3-(2.4^x(2)*x(1)+exp(x(2)*log(x(3)))))^2+(3.4-(2.6^x(2)*x(1)+exp(x(2)*log(x(3)))))^2+(3.8-(2.8^x(2)*x(1)+exp(x(2)*log(x(3)))))^2;

% Bounds
lb = [0,0,0]';
ub = [5,5,5]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','model42');
opts.sense = 'min';
