% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:05
% Model: model45

% Objective
fun = @(x)(16.7242-exp(x(3))*x(2)-x(1))^2+(16.8262-exp(5*x(3))*x(2)-x(1))^2+(16.9657-exp(10*x(3))*x(2)-x(1))^2+(17.1198-exp(15*x(3))*x(2)-x(1))^2+(17.2902-exp(20*x(3))*x(2)-x(1))^2+(17.4785-exp(25*x(3))*x(2)-x(1))^2+(17.6865-exp(30*x(3))*x(2)-x(1))^2+(17.9165-exp(35*x(3))*x(2)-x(1))^2+(18.1706-exp(40*x(3))*x(2)-x(1))^2+(18.7619-exp(50*x(3))*x(2)-x(1))^2;

% Bounds
lb = [0,0,0]';
ub = [1000,10,2]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','model45');
opts.sense = 'min';
