% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:05
% Model: model33

% Objective
fun = @(x)(40-2*x(3))^2+(10-(exp(-0.6*x(1))*x(3)+exp(-0.4*x(2))*x(3)))^2+(5-(exp(-0.6*x(1))*x(3)+exp(-x(2))*x(3)))^2+(2.5-(exp(-1.4*x(1))*x(3)+exp(-1.4*x(2))*x(3)))^2+(2.5-(exp(-2.6*x(1))*x(3)+exp(-1.4*x(2))*x(3)))^2+(2-(exp(-3.2*x(1))*x(3)+exp(-1.6*x(2))*x(3)))^2+(1-(exp(-0.8*x(1))*x(3)+exp(-2*x(2))*x(3)))^2+(0.7-(exp(-1.6*x(1))*x(3)+exp(-2.2*x(2))*x(3)))^2+(0.8-(exp(-2.6*x(1))*x(3)+exp(-2.2*x(2))*x(3)))^2+(0.7-(exp(-4*x(1))*x(3)+exp(-2.2*x(2))*x(3)))^2+(0.4-(exp(-1.2*x(1))*x(3)+exp(-2.6*x(2))*x(3)))^2+(0.4-(exp(-2*x(1))*x(3)+exp(-2.6*x(2))*x(3)))^2+(0.3-(exp(-4.6*x(1))*x(3)+exp(-2.8*x(2))*x(3)))^2+(0.22-(exp(-3.2*x(1))*x(3)+exp(-3*x(2))*x(3)))^2+(0.2-(exp(-1.6*x(1))*x(3)+exp(-3.2*x(2))*x(3)))^2+(0.1-(exp(-4.2*x(1))*x(3)+exp(-3.4*x(2))*x(3)))^2+(0.05-(exp(-2*x(1))*x(3)+exp(-3.8*x(2))*x(3)))^2+(0.07-(exp(-3.2*x(1))*x(3)+exp(-3.8*x(2))*x(3)))^2+(0.03-(exp(-2.8*x(1))*x(3)+exp(-4.2*x(2))*x(3)))^2+(0.03-(exp(-4.2*x(1))*x(3)+exp(-4.2*x(2))*x(3)))^2+(0.03-(exp(-5.4*x(1))*x(3)+exp(-4.4*x(2))*x(3)))^2+(0.02-(exp(-5.6*x(1))*x(3)+exp(-4.8*x(2))*x(3)))^2+(0.01-(exp(-3.2*x(1))*x(3)+exp(-5*x(2))*x(3)))^2;

% Bounds
lb = [0,0,0]';
ub = [1000,1000,1000]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','model33');
opts.sense = 'min';
