% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:05
% Model: model15

% Objective
fun = @(x)(2.5134-x(1)-x(3)-x(5))^2+(2.0443-(exp(-0.05*x(2))*x(1)+exp(-0.05*x(4))*x(3)+exp(-0.05*x(6))*x(5)))^2+(1.6684-(exp(-0.1*x(2))*x(1)+exp(-0.1*x(4))*x(3)+exp(-0.1*x(6))*x(5)))^2+(1.3664-(exp(-0.15*x(2))*x(1)+exp(-0.15*x(4))*x(3)+exp(-0.15*x(6))*x(5)))^2+(1.1232-(exp(-0.2*x(2))*x(1)+exp(-0.2*x(4))*x(3)+exp(-0.2*x(6))*x(5)))^2+(0.9269-(exp(-0.25*x(2))*x(1)+exp(-0.25*x(4))*x(3)+exp(-0.25*x(6))*x(5)))^2+(0.7679-(exp(-0.3*x(2))*x(1)+exp(-0.3*x(4))*x(3)+exp(-0.3*x(6))*x(5)))^2+(0.6389-(exp(-0.35*x(2))*x(1)+exp(-0.35*x(4))*x(3)+exp(-0.35*x(6))*x(5)))^2+(0.5338-(exp(-0.4*x(2))*x(1)+exp(-0.4*x(4))*x(3)+exp(-0.4*x(6))*x(5)))^2+(0.4479-(exp(-0.45*x(2))*x(1)+exp(-0.45*x(4))*x(3)+exp(-0.45*x(6))*x(5)))^2+(0.3776-(exp(-0.5*x(2))*x(1)+exp(-0.5*x(4))*x(3)+exp(-0.5*x(6))*x(5)))^2+(0.3197-(exp(-0.55*x(2))*x(1)+exp(-0.55*x(4))*x(3)+exp(-0.55*x(6))*x(5)))^2+(0.272-(exp(-0.6*x(2))*x(1)+exp(-0.6*x(4))*x(3)+exp(-0.6*x(6))*x(5)))^2+(0.2325-(exp(-0.65*x(2))*x(1)+exp(-0.65*x(4))*x(3)+exp(-0.65*x(6))*x(5)))^2+(0.1997-(exp(-0.7*x(2))*x(1)+exp(-0.7*x(4))*x(3)+exp(-0.7*x(6))*x(5)))^2+(0.1723-(exp(-0.75*x(2))*x(1)+exp(-0.75*x(4))*x(3)+exp(-0.75*x(6))*x(5)))^2+(0.1493-(exp(-0.8*x(2))*x(1)+exp(-0.8*x(4))*x(3)+exp(-0.8*x(6))*x(5)))^2+(0.1301-(exp(-0.85*x(2))*x(1)+exp(-0.85*x(4))*x(3)+exp(-0.85*x(6))*x(5)))^2+(0.1138-(exp(-0.9*x(2))*x(1)+exp(-0.9*x(4))*x(3)+exp(-0.9*x(6))*x(5)))^2+(0.1-(exp(-0.95*x(2))*x(1)+exp(-0.95*x(4))*x(3)+exp(-0.95*x(6))*x(5)))^2+(0.0883-(exp(-x(2))*x(1)+exp(-x(4))*x(3)+exp(-x(6))*x(5)))^2+(0.0783-(exp(-1.05*x(2))*x(1)+exp(-1.05*x(4))*x(3)+exp(-1.05*x(6))*x(5)))^2+(0.0698-(exp(-1.1*x(2))*x(1)+exp(-1.1*x(4))*x(3)+exp(-1.1*x(6))*x(5)))^2+(0.0624-(exp(-1.15*x(2))*x(1)+exp(-1.15*x(4))*x(3)+exp(-1.15*x(6))*x(5)))^2;

% Bounds
lb = [0,0,0,0,0,0]';
ub = [1,1,1,6,6,6]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','model15');
opts.sense = 'min';
