% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:04
% Model: model13

% Objective
fun = @(x)(2.5134-x(1)-x(3)-x(5))^2+(2.044333373291-(exp(-0.05*x(2))*x(1)+exp(-0.05*x(4))*x(3)+exp(-0.05*x(6))*x(5)))^2+(1.668404436564-(exp(-0.1*x(2))*x(1)+exp(-0.1*x(4))*x(3)+exp(-0.1*x(6))*x(5)))^2+(1.366418021208-(exp(-0.15*x(2))*x(1)+exp(-0.15*x(4))*x(3)+exp(-0.15*x(6))*x(5)))^2+(1.123232487372-(exp(-0.2*x(2))*x(1)+exp(-0.2*x(4))*x(3)+exp(-0.2*x(6))*x(5)))^2+(0.9268897180037-(exp(-0.25*x(2))*x(1)+exp(-0.25*x(4))*x(3)+exp(-0.25*x(6))*x(5)))^2+(0.7679338563728-(exp(-0.3*x(2))*x(1)+exp(-0.3*x(4))*x(3)+exp(-0.3*x(6))*x(5)))^2+(0.6388775523106-(exp(-0.35*x(2))*x(1)+exp(-0.35*x(4))*x(3)+exp(-0.35*x(6))*x(5)))^2+(0.5337835317402-(exp(-0.4*x(2))*x(1)+exp(-0.4*x(4))*x(3)+exp(-0.4*x(6))*x(5)))^2+(0.4479363617347-(exp(-0.45*x(2))*x(1)+exp(-0.45*x(4))*x(3)+exp(-0.45*x(6))*x(5)))^2+(0.377584788435-(exp(-0.5*x(2))*x(1)+exp(-0.5*x(4))*x(3)+exp(-0.5*x(6))*x(5)))^2+(0.3197393199326-(exp(-0.55*x(2))*x(1)+exp(-0.55*x(4))*x(3)+exp(-0.55*x(6))*x(5)))^2+(0.2720130773746-(exp(-0.6*x(2))*x(1)+exp(-0.6*x(4))*x(3)+exp(-0.6*x(6))*x(5)))^2+(0.2324965529032-(exp(-0.65*x(2))*x(1)+exp(-0.65*x(4))*x(3)+exp(-0.65*x(6))*x(5)))^2+(0.1996589546065-(exp(-0.7*x(2))*x(1)+exp(-0.7*x(4))*x(3)+exp(-0.7*x(6))*x(5)))^2+(0.1722704126914-(exp(-0.75*x(2))*x(1)+exp(-0.75*x(4))*x(3)+exp(-0.75*x(6))*x(5)))^2+(0.1493405660168-(exp(-0.8*x(2))*x(1)+exp(-0.8*x(4))*x(3)+exp(-0.8*x(6))*x(5)))^2+(0.1300700206922-(exp(-0.85*x(2))*x(1)+exp(-0.85*x(4))*x(3)+exp(-0.85*x(6))*x(5)))^2+(0.1138119324644-(exp(-0.9*x(2))*x(1)+exp(-0.9*x(4))*x(3)+exp(-0.9*x(6))*x(5)))^2+(0.1000415587559-(exp(-0.95*x(2))*x(1)+exp(-0.95*x(4))*x(3)+exp(-0.95*x(6))*x(5)))^2+(0.0883320908454-(exp(-x(2))*x(1)+exp(-x(4))*x(3)+exp(-x(6))*x(5)))^2+(0.0783354401935-(exp(-1.05*x(2))*x(1)+exp(-1.05*x(4))*x(3)+exp(-1.05*x(6))*x(5)))^2+(0.06976693743449-(exp(-1.1*x(2))*x(1)+exp(-1.1*x(4))*x(3)+exp(-1.1*x(6))*x(5)))^2+(0.06239312536719-(exp(-1.15*x(2))*x(1)+exp(-1.15*x(4))*x(3)+exp(-1.15*x(6))*x(5)))^2;

% Bounds
lb = [0,0,0,0,0,0]';
ub = [1,2,1,4,2,6]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','model13');
opts.sense = 'min';
