% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:05
% Model: model4

% Objective
fun = @(x)(16.7-exp(x(3))*x(2)-x(1))^2+(16.8-exp(5*x(3))*x(2)-x(1))^2+(16.9-exp(10*x(3))*x(2)-x(1))^2+(17.1-exp(15*x(3))*x(2)-x(1))^2+(17.2-exp(20*x(3))*x(2)-x(1))^2+(17.4-exp(25*x(3))*x(2)-x(1))^2+(17.6-exp(30*x(3))*x(2)-x(1))^2+(17.9-exp(35*x(3))*x(2)-x(1))^2+(18.1-exp(40*x(3))*x(2)-x(1))^2+(18.7-exp(50*x(3))*x(2)-x(1))^2;

% Bounds
lb = [0,0,0]';
ub = [1000,1000,1]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','model4');
opts.sense = 'min';
