% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:10:05
% Model: model2

% Objective
fun = @(x)(109-(1-exp(-x(2)))*x(1))^2+(149-(1-exp(-2*x(2)))*x(1))^2+(149-(1-exp(-3*x(2)))*x(1))^2+(191-(1-exp(-5*x(2)))*x(1))^2+(213-(1-exp(-7*x(2)))*x(1))^2+(224-(1-exp(-10*x(2)))*x(1))^2;

% Bounds
lb = [-100,-1]';
ub = [1000,100]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','model2');
opts.sense = 'min';
