% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:02:31
% Model: Neumaier3

% Objective
fun = @(x)(-1+x(1))^2+(-1+x(2))^2+(-1+x(3))^2+(-1+x(4))^2+(-1+x(5))^2+(-1+x(6))^2+(-1+x(7))^2+(-1+x(8))^2+(-1+x(9))^2+(-1+x(10))^2-(x(2)*x(1)+x(3)*x(2)+x(4)*x(3)+x(5)*x(4)+x(6)*x(5)+x(7)*x(6)+x(8)*x(7)+x(9)*x(8)+x(10)*x(9));

% Bounds
lb = [-100,-100,-100,-100,-100,-100,-100,-100,-100,-100]';
ub = [100,100,100,100,100,100,100,100,100,100]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','Neumaier3');
opts.sense = 'min';
