% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:02:31
% Model: Neumaier2

% Objective
fun = @(x)(8-x(1)-x(2)-x(3)-x(4))^2+(18-(x(1)^2+x(2)^2+x(3)^2+x(4)^2))^2+(44-(x(1)^3+x(2)^3+x(3)^3+x(4)^3))^2+(114-(x(1)^4+x(2)^4+x(3)^4+x(4)^4))^2;

% Bounds
lb = [0,0,0,0]';
ub = [1,2,3,4]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','Neumaier2');
opts.sense = 'min';
