% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:11:48
% Model: oslbqp

% Objective
fun = @(x)0.5*(x(1)^2+x(2)^2+x(3)^2+x(4)^2+x(5)^2+x(6)^2+x(7)^2+x(8)^2)+x(1)+2*x(5)-x(8);

% Bounds
lb = [2.5,0,0,0,0.5,0,0,0]';
ub = [Inf,4.1,Inf,Inf,4,Inf,Inf,4.3]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [2.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]';

% Options
opts = struct('probname','oslbqp');
opts.sense = 'min';
