% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:02:31
% Model: PowellQ

% Objective
fun = @(x)121*x(1)*x(1)+(5*x(3)-5*x(4))*(x(3)-x(4))+(x(2)-2*x(3))^4+10*(x(1)-x(4))^4;

% Bounds
lb = [-10,-10,-10,-10]';
ub = [10,10,10,10]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','PowellQ');
opts.sense = 'min';
