% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:11:50
% Model: prob09

% Objective
fun = @(x)x(1);

% Bounds
lb = [-100,-2,-2]';
ub = [100,2,2]';

% Constraints
nlcon = @(x)[100*(x(3)-x(2)^2)^2+(1-x(2))^2-x(1)];
cl = 0';
cu = 0';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [2.28067255148468e-06,0.999139149741104,0.998154959548312]';

% Options
opts = struct('probname','prob09');
opts.sense = 'min';
