% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:09
% Model: qudlin

% Objective
fun = @(x)x(1)*x(2)+x(2)*x(3)+x(3)*x(4)+x(4)*x(5)+x(5)*x(6)+x(6)*x(7)-10*x(1)-20*x(2)-30*x(3)-40*x(4)-50*x(5)-60*x(6)-70*x(7)-80*x(8)-90*x(9)-100*x(10)-110*x(11)-120*x(12);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [10,10,10,10,10,10,10,10,10,10,10,10]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','qudlin');
opts.sense = 'min';
