% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:09
% Model: ratkbates

% Objective
fun = @(x)(34780-x(2)/(50+x(3))+x(1))^2+(28610-x(2)/(55+x(3))+x(1))^2+(23650-x(2)/(60+x(3))+x(1))^2+(19630-x(2)/(65+x(3))+x(1))^2+(16370-x(2)/(70+x(3))+x(1))^2+(13720-x(2)/(75+x(3))+x(1))^2+(11540-x(2)/(80+x(3))+x(1))^2+(9744-x(2)/(85+x(3))+x(1))^2+(8261-x(2)/(90+x(3))+x(1))^2+(7030-x(2)/(95+x(3))+x(1))^2+(6005-x(2)/(100+x(3))+x(1))^2+(5147-x(2)/(105+x(3))+x(1))^2+(4427-x(2)/(110+x(3))+x(1))^2+(3820-x(2)/(115+x(3))+x(1))^2+(3307-x(2)/(120+x(3))+x(1))^2+(2872-x(2)/(125+x(3))+x(1))^2;

% Bounds
lb = [0,0,0]';
ub = [1000,100000,10000]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','ratkbates');
opts.sense = 'min';
