% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:09
% Model: s204

% Objective
fun = @(x)(0.13294+1.2537*(x(1)*(5.66598*x(1)+2.77141*x(2))+x(2)*(2.77141*x(1)+2.12413*x(2)))-0.564255*x(1)+0.392417*x(2))^2+(0.244378+(-0.682005*(x(1)*(5.66598*x(1)+2.77141*x(2))+x(2)*(2.77141*x(1)+2.12413*x(2))))-0.404979*x(1)+0.927589*x(2))^2+(0.325895+0.51141*(x(1)*(5.66598*x(1)+2.77141*x(2))+x(2)*(2.77141*x(1)+2.12413*x(2)))-0.0735084*x(1)+0.535493*x(2))^2;

% Bounds
lb = [-Inf,-Inf]';
ub = [Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [0.1,0.1]';

% Options
opts = struct('probname','s204');
opts.sense = 'min';
