% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:09
% Model: s244

% Objective
fun = @(x)(0.934559787821252+exp(-0.1*x(1))-exp(-0.1*x(2))*x(3))^2+(-0.142054336894918+exp(-0.2*x(1))-exp(-0.2*x(2))*x(3))^2+(-0.491882878842398+exp(-0.3*x(1))-exp(-0.3*x(2))*x(3))^2;

% Bounds
lb = [0,0,0]';
ub = [10,10,10]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [1,2,1]';

% Options
opts = struct('probname','s244');
opts.sense = 'min';
