% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:09
% Model: s273

% Objective
fun = @(x)10*(15*(-1+x(1))^2+10*(15*(-1+x(1))^2+14*(-1+x(2))^2+13*(-1+x(3))^2+12*(-1+x(4))^2+11*(-1+x(5))^2+10*(-1+x(6))^2)^2+14*(-1+x(2))^2+10*(15*(-1+x(1))^2+14*(-1+x(2))^2+13*(-1+x(3))^2+12*(-1+x(4))^2+11*(-1+x(5))^2+10*(-1+x(6))^2)^2+13*(-1+x(3))^2+10*(15*(-1+x(1))^2+14*(-1+x(2))^2+13*(-1+x(3))^2+12*(-1+x(4))^2+11*(-1+x(5))^2+10*(-1+x(6))^2)^2+12*(-1+x(4))^2+10*(15*(-1+x(1))^2+14*(-1+x(2))^2+13*(-1+x(3))^2+12*(-1+x(4))^2+11*(-1+x(5))^2+10*(-1+x(6))^2)^2+11*(-1+x(5))^2+10*(15*(-1+x(1))^2+14*(-1+x(2))^2+13*(-1+x(3))^2+12*(-1+x(4))^2+11*(-1+x(5))^2+10*(-1+x(6))^2)^2+10*(-1+x(6))^2+10*(15*(-1+x(1))^2+14*(-1+x(2))^2+13*(-1+x(3))^2+12*(-1+x(4))^2+11*(-1+x(5))^2+10*(-1+x(6))^2)^2);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s273');
opts.sense = 'min';
