% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:09
% Model: s276

% Objective
fun = @(x)x(1)*(x(1)+0.5*x(2)+0.333333333333333*x(3)+0.25*x(4)+0.2*x(5)+0.166666666666667*x(6))+x(2)*(0.5*x(1)+0.333333333333333*x(2)+0.25*x(3)+0.2*x(4)+0.166666666666667*x(5)+0.142857142857143*x(6))+x(3)*(0.333333333333333*x(1)+0.25*x(2)+0.2*x(3)+0.166666666666667*x(4)+0.142857142857143*x(5)+0.125*x(6))+x(4)*(0.25*x(1)+0.2*x(2)+0.166666666666667*x(3)+0.142857142857143*x(4)+0.125*x(5)+0.111111111111111*x(6))+x(5)*(0.2*x(1)+0.166666666666667*x(2)+0.142857142857143*x(3)+0.125*x(4)+0.111111111111111*x(5)+0.1*x(6))+x(6)*(0.166666666666667*x(1)+0.142857142857143*x(2)+0.125*x(3)+0.111111111111111*x(4)+0.1*x(5)+0.0909090909090909*x(6));

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,-0.8,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [-4,-2,-1.333,-1,-0.8,0.6667]';

% Options
opts = struct('probname','s276');
opts.sense = 'min';
