% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:09
% Model: s282

% Objective
fun = @(x)(-1+x(1))^2+(-1+x(10))^2+10*(9*(x(1)^2-x(2))^2+8*(x(2)^2-x(3))^2+7*(x(3)^2-x(4))^2+6*(x(4)^2-x(5))^2+5*(x(5)^2-x(6))^2+4*(x(6)^2-x(7))^2+3*(x(7)^2-x(8))^2+2*(x(8)^2-x(9))^2+(x(9)^2-x(10))^2);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [-1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s282');
opts.sense = 'min';
