% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:09
% Model: s283

% Objective
fun = @(x)((-1+x(1))^2)^3+8*((-1+x(2))^2)^3+27*((-1+x(3))^2)^3+64*((-1+x(4))^2)^3+125*((-1+x(5))^2)^3+216*((-1+x(6))^2)^3+343*((-1+x(7))^2)^3+512*((-1+x(8))^2)^3+729*((-1+x(9))^2)^3+1000*((-1+x(10))^2)^3;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s283');
opts.sense = 'min';
