% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:09
% Model: s287

% Objective
fun = @(x)100*(x(1)^2-x(6))^2+(-1+x(1))^2+90*(x(11)^2-x(16))^2+(-1+x(11))^2+10.1*((-1+x(6))^2+(-1+x(16))^2)+(-19.8+19.8*x(6))*(-1+x(16))+100*(x(2)^2-x(7))^2+(-1+x(2))^2+90*(x(12)^2-x(17))^2+(-1+x(12))^2+10.1*((-1+x(7))^2+(-1+x(17))^2)+(-19.8+19.8*x(7))*(-1+x(17))+100*(x(3)^2-x(8))^2+(-1+x(3))^2+90*(x(13)^2-x(18))^2+(-1+x(13))^2+10.1*((-1+x(8))^2+(-1+x(18))^2)+(-19.8+19.8*x(8))*(-1+x(18))+100*(x(4)^2-x(9))^2+(-1+x(4))^2+90*(x(14)^2-x(19))^2+(-1+x(14))^2+10.1*((-1+x(9))^2+(-1+x(19))^2)+(-19.8+19.8*x(9))*(-1+x(19))+100*(x(5)^2-x(10))^2+(-1+x(5))^2+90*(x(15)^2-x(20))^2+(-1+x(15))^2+10.1*((-1+x(10))^2+(-1+x(20))^2)+(-19.8+19.8*x(10))*(-1+x(20));

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [-3,-3,-3,-3,-3,-1,-1,-1,-1,-1,-3,-3,-3,-3,-3,-1,-1,-1,-1,-1]';

% Options
opts = struct('probname','s287');
opts.sense = 'min';
