% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:10
% Model: s288

% Objective
fun = @(x)(x(1)+10*x(6))^2+5*(x(11)-x(16))^2+(x(6)-2*x(11))^4+10*(x(1)-x(16))^4+(x(2)+10*x(7))^2+5*(x(12)-x(17))^2+(x(7)-2*x(12))^4+10*(x(2)-x(17))^4+(x(3)+10*x(8))^2+5*(x(13)-x(18))^2+(x(8)-2*x(13))^4+10*(x(3)-x(18))^4+(x(4)+10*x(9))^2+5*(x(14)-x(19))^2+(x(9)-2*x(14))^4+10*(x(4)-x(19))^4+(x(5)+10*x(10))^2+5*(x(15)-x(20))^2+(x(10)-2*x(15))^4+10*(x(5)-x(20))^4;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [3,3,3,3,3,-1,-1,-1,-1,-1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1]';

% Options
opts = struct('probname','s288');
opts.sense = 'min';
