% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:10
% Model: s291

% Objective
fun = @(x)x(1)*x(1)+2*x(2)*x(2)+3*x(3)*x(3)+4*x(4)*x(4)+5*x(5)*x(5)+6*x(6)*x(6)+7*x(7)*x(7)+8*x(8)*x(8)+9*x(9)*x(9)+10*x(10)*x(10);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [1,1,1,1,1,1,1,1,1,1]';

% Options
opts = struct('probname','s291');
opts.sense = 'min';
