% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:10
% Model: s300

% Objective
fun = @(x)x(1)*(x(1)-x(2))+x(2)*(2*x(2)-x(1)-x(3))+x(3)*(2*x(3)-x(2)-x(4))+x(4)*(2*x(4)-x(3)-x(5))+x(5)*(2*x(5)-x(4)-x(6))+x(6)*(2*x(6)-x(5)-x(7))+x(7)*(2*x(7)-x(6)-x(8))+x(8)*(2*x(8)-x(7)-x(9))+x(9)*(2*x(9)-x(8)-x(10))+x(10)*(2*x(10)-x(9)-x(11))+x(11)*(2*x(11)-x(10)-x(12))+x(12)*(2*x(12)-x(11)-x(13))+x(13)*(2*x(13)-x(12)-x(14))+x(14)*(2*x(14)-x(13)-x(15))+x(15)*(2*x(15)-x(14)-x(16))+x(16)*(2*x(16)-x(15)-x(17))+x(17)*(2*x(17)-x(16)-x(18))+x(18)*(2*x(18)-x(17)-x(19))+x(19)*(2*x(19)-x(18)-x(20))+x(20)*(2*x(20)-x(19))-2*x(1);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s300');
opts.sense = 'min';
