% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:10
% Model: s333

% Objective
fun = @(x)(1-0.013869625520111*exp(-4*x(2))*x(1)-0.013869625520111*x(3))^2+(1-0.0152439024390244*exp(-5.75*x(2))*x(1)-0.0152439024390244*x(3))^2+(1-0.0178890876565295*exp(-7.5*x(2))*x(1)-0.0178890876565295*x(3))^2+(1-0.0584795321637427*exp(-24*x(2))*x(1)-0.0584795321637427*x(3))^2+(1-0.102040816326531*exp(-32*x(2))*x(1)-0.102040816326531*x(3))^2+(1-0.222222222222222*exp(-48*x(2))*x(1)-0.222222222222222*x(3))^2+(1-0.769230769230769*exp(-72*x(2))*x(1)-0.769230769230769*x(3))^2+(1-1.66666666666667*exp(-96*x(2))*x(1)-1.66666666666667*x(3))^2;

% Bounds
lb = [-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [30,NaN,3]';

% Options
opts = struct('probname','s333');
opts.sense = 'min';
