% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:10
% Model: schwefel

% Objective
fun = @(x)x(1)^10+x(2)^10+x(3)^10+x(4)^10+x(5)^10;

% Bounds
lb = [-0.5,-0.5,-0.5,-0.5,-0.5]';
ub = [0.4,0.4,0.4,0.4,0.4]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [0.4,0.4,0.4,0.4,0.4]';

% Options
opts = struct('probname','schwefel');
opts.sense = 'min';
