% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:29
% Model: st_cqpjk2

% Objective
fun = @(x)9*x(1)*x(1)-15*x(1)+9*x(2)*x(2)-12*x(2)+9*x(3)*x(3)-9*x(3);

% Bounds
lb = [0,0,0]';
ub = [1,1,1]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','st_cqpjk2');
opts.sense = 'min';
