% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:30
% Model: tre

% Objective
fun = @(x)x(1)^4+4*x(1)^3+4*x(1)^2+x(2)^2;

% Bounds
lb = [-5,-5]';
ub = [5,5]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [-1.1,0.1]';

% Options
opts = struct('probname','tre');
opts.sense = 'min';
