% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:12:50
% Model: weibull3

% Objective
fun = @(x)(1.23+exp(-0^x(4)*x(3))*x(2)-x(1))^2+(1.52+exp(-1^x(4)*x(3))*x(2)-x(1))^2+(2.95+exp(-2^x(4)*x(3))*x(2)-x(1))^2+(4.34+exp(-3^x(4)*x(3))*x(2)-x(1))^2+(5.26+exp(-4^x(4)*x(3))*x(2)-x(1))^2+(5.84+exp(-5^x(4)*x(3))*x(2)-x(1))^2+(6.21+exp(-6^x(4)*x(3))*x(2)-x(1))^2+(6.5+exp(-8^x(4)*x(3))*x(2)-x(1))^2+(6.83+exp(-10^x(4)*x(3))*x(2)-x(1))^2;

% Bounds
lb = [0,0,0,0]';
ub = [100,100,1,10]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','weibull3');
opts.sense = 'min';
