% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 06-Jun-2016 04:13:18
% Model: zhenglog

% Objective
fun = @(x)(8.93-x(1)/(1+exp(x(2)-9*x(3))))^2+(10.8-x(1)/(1+exp(x(2)-14*x(3))))^2+(18.59-x(1)/(1+exp(x(2)-21*x(3))))^2+(22.33-x(1)/(1+exp(x(2)-28*x(3))))^2+(39.35-x(1)/(1+exp(x(2)-42*x(3))))^2+(56.11-x(1)/(1+exp(x(2)-57*x(3))))^2+(61.73-x(1)/(1+exp(x(2)-63*x(3))))^2+(64.62-x(1)/(1+exp(x(2)-70*x(3))))^2+(67.08-x(1)/(1+exp(x(2)-79*x(3))))^2;

% Bounds
lb = [0,0,0]';
ub = [100,5,1]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','zhenglog');
opts.sense = 'min';
